-- Instalación en PostgreSQL 14+; conectar primero a la base CRM_N8N.
-- No ejecutar los scripts MySQL/Workbench en esta base.
-- DDL transaccional, sin borrar datos. El usuario instalador será propietario.
BEGIN;
CREATE SCHEMA IF NOT EXISTS wflow;
REVOKE CREATE ON SCHEMA wflow FROM PUBLIC;

CREATE TABLE IF NOT EXISTS wflow.gestiones (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workflow_session varchar(100) COLLATE "C" NOT NULL UNIQUE,
    usuario_asesor varchar(100) NOT NULL,
    numero_conexion varchar(100) NOT NULL,
    pqr varchar(100) NOT NULL,
    created_at timestamptz(3) NOT NULL DEFAULT statement_timestamp(),
    updated_at timestamptz(3) NOT NULL DEFAULT statement_timestamp(),
    CONSTRAINT gestion_datos_validos CHECK (
        btrim(workflow_session) <> '' AND btrim(usuario_asesor) <> ''
        AND btrim(numero_conexion) <> '' AND btrim(pqr) <> ''
        AND (workflow_session || usuario_asesor || numero_conexion || pqr) !~ '[[:cntrl:]]'
    )
);
CREATE INDEX IF NOT EXISTS ix_gestiones_asesor ON wflow.gestiones (usuario_asesor);
CREATE INDEX IF NOT EXISTS ix_gestiones_conexion ON wflow.gestiones (numero_conexion);
CREATE INDEX IF NOT EXISTS ix_gestiones_pqr ON wflow.gestiones (pqr);

CREATE TABLE IF NOT EXISTS wflow.gestiones_log (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workflow_session varchar(100) COLLATE "C" NOT NULL
        REFERENCES wflow.gestiones(workflow_session) ON DELETE RESTRICT,
    codigo_flujo varchar(100) NOT NULL,
    nombre_flujo varchar(180) NOT NULL,
    codigo_etapa varchar(100) NOT NULL,
    nombre_etapa varchar(180) NOT NULL,
    numero_etapa integer NOT NULL CHECK (numero_etapa >= 0),
    numero_intento integer NOT NULL DEFAULT 1 CHECK (numero_intento > 0),
    execution_id varchar(100),
    workflow_version varchar(100),
    estado_gestion varchar(32) NOT NULL,
    resultado varchar(100) NOT NULL,
    next_step varchar(100) NOT NULL,
    respuestas_json jsonb NOT NULL DEFAULT '{}'::jsonb,
    contexto_json jsonb NOT NULL DEFAULT '{}'::jsonb,
    error_json jsonb,
    usuario_asesor varchar(100) NOT NULL,
    numero_conexion varchar(100) NOT NULL,
    pqr varchar(100) NOT NULL,
    created_at timestamptz(3) NOT NULL DEFAULT statement_timestamp(),
    updated_at timestamptz(3) NOT NULL DEFAULT statement_timestamp(),
    CONSTRAINT uq_log_etapa_intento UNIQUE
        (workflow_session, codigo_flujo, codigo_etapa, numero_intento),
    CONSTRAINT log_json_objetos CHECK (
        jsonb_typeof(respuestas_json) = 'object' AND jsonb_typeof(contexto_json) = 'object'
    ),
    CONSTRAINT log_codigos_validos CHECK (
        btrim(codigo_flujo) <> '' AND btrim(codigo_etapa) <> ''
        AND btrim(estado_gestion) <> '' AND btrim(resultado) <> '' AND btrim(next_step) <> ''
    ),
    CONSTRAINT log_etapa_inicial CHECK (
        (numero_etapa = 0 AND codigo_flujo = 'inicioGestion'
         AND codigo_etapa = 'registroInicial' AND resultado = 'datos_iniciales_registrados')
        OR (numero_etapa > 0 AND codigo_flujo <> 'inicioGestion')
    )
);
CREATE INDEX IF NOT EXISTS ix_log_sesion ON wflow.gestiones_log
    (workflow_session, codigo_flujo, numero_etapa, created_at);
CREATE INDEX IF NOT EXISTS ix_log_resultado ON wflow.gestiones_log
    (codigo_flujo, codigo_etapa, resultado, created_at);
CREATE INDEX IF NOT EXISTS ix_log_estado ON wflow.gestiones_log
    (codigo_flujo, estado_gestion, updated_at);

CREATE OR REPLACE FUNCTION wflow.proteger_inicio() RETURNS trigger
LANGUAGE plpgsql SET search_path = pg_catalog, pg_temp AS $$
BEGIN
    IF (NEW.workflow_session, NEW.usuario_asesor, NEW.numero_conexion, NEW.pqr, NEW.created_at)
       IS DISTINCT FROM
       (OLD.workflow_session, OLD.usuario_asesor, OLD.numero_conexion, OLD.pqr, OLD.created_at) THEN
        RAISE EXCEPTION 'Los datos iniciales de la gestión son inmutables' USING ERRCODE = '23514';
    END IF;
    NEW.updated_at := statement_timestamp();
    RETURN NEW;
END $$;
DROP TRIGGER IF EXISTS proteger_inicio ON wflow.gestiones;
CREATE TRIGGER proteger_inicio BEFORE UPDATE ON wflow.gestiones
FOR EACH ROW EXECUTE FUNCTION wflow.proteger_inicio();

CREATE OR REPLACE FUNCTION wflow.copiar_datos_iniciales() RETURNS trigger
LANGUAGE plpgsql SET search_path = pg_catalog, pg_temp AS $$
DECLARE inicio wflow.gestiones%ROWTYPE; datos jsonb;
BEGIN
    IF TG_OP = 'UPDATE' THEN
        IF (NEW.workflow_session, NEW.codigo_flujo, NEW.codigo_etapa, NEW.numero_intento, NEW.created_at)
           IS DISTINCT FROM
           (OLD.workflow_session, OLD.codigo_flujo, OLD.codigo_etapa, OLD.numero_intento, OLD.created_at) THEN
            RAISE EXCEPTION 'No se puede reasignar un registro del log' USING ERRCODE = '23514';
        END IF;
    END IF;
    SELECT * INTO inicio FROM wflow.gestiones WHERE workflow_session = NEW.workflow_session;
    IF NOT FOUND THEN
        RAISE EXCEPTION 'La gestión requiere un registro inicial' USING ERRCODE = '23503';
    END IF;
    IF NEW.numero_etapa > 0 AND NOT EXISTS (
        SELECT 1 FROM wflow.gestiones_log
        WHERE workflow_session = NEW.workflow_session AND codigo_flujo = 'inicioGestion'
          AND codigo_etapa = 'registroInicial' AND resultado = 'datos_iniciales_registrados'
    ) THEN
        RAISE EXCEPTION 'El log inicial debe estar confirmado antes del diagnóstico' USING ERRCODE = '23503';
    END IF;
    NEW.usuario_asesor := inicio.usuario_asesor;
    NEW.numero_conexion := inicio.numero_conexion;
    NEW.pqr := inicio.pqr;
    datos := jsonb_build_object('usuario_asesor', inicio.usuario_asesor,
        'numero_conexion', inicio.numero_conexion, 'pqr', inicio.pqr);
    NEW.respuestas_json := COALESCE(NEW.respuestas_json, '{}'::jsonb) || datos;
    NEW.contexto_json := COALESCE(NEW.contexto_json, '{}'::jsonb) || datos;
    NEW.updated_at := statement_timestamp();
    RETURN NEW;
END $$;
DROP TRIGGER IF EXISTS copiar_datos_iniciales ON wflow.gestiones_log;
CREATE TRIGGER copiar_datos_iniciales BEFORE INSERT OR UPDATE ON wflow.gestiones_log
FOR EACH ROW EXECUTE FUNCTION wflow.copiar_datos_iniciales();

-- Una llamada es una única sentencia/transacción: cabecera y log son atómicos.
-- Solo INSERT: no valida usuarios existentes ni modifica cabeceras/logs previos.
-- Los conflictos se refieren a la misma sesión, nunca al usuario del asesor.
CREATE OR REPLACE FUNCTION wflow.registrar_inicio_gestion(
    p_session text, p_datos jsonb, p_execution_id text, p_version text
) RETURNS TABLE ("registroConfirmado" integer, "workflowSession" text,
    "usuarioAsesor" text, "numeroConexion" text, pqr text)
LANGUAGE plpgsql SET search_path = pg_catalog, pg_temp AS $$
DECLARE inicio wflow.gestiones%ROWTYPE; campo text; valor text; datos jsonb;
BEGIN
    IF p_session IS NULL OR btrim(p_session) = '' OR length(p_session) > 100
       OR p_session ~ '[[:cntrl:]]' THEN
        RAISE EXCEPTION 'Referencia de gestión inválida' USING ERRCODE = '22023';
    END IF;
    IF p_datos IS NULL OR jsonb_typeof(p_datos) <> 'object' THEN
        RAISE EXCEPTION 'Los datos iniciales deben ser un objeto JSON' USING ERRCODE = '22023';
    END IF;
    FOREACH campo IN ARRAY ARRAY['usuario_asesor', 'numero_conexion', 'pqr'] LOOP
        valor := p_datos ->> campo;
        IF jsonb_typeof(p_datos -> campo) IS DISTINCT FROM 'string'
           OR btrim(valor) = '' OR length(valor) > 100 OR valor ~ '[[:cntrl:]]' THEN
            RAISE EXCEPTION 'Dato inicial inválido: %', campo USING ERRCODE = '22023';
        END IF;
    END LOOP;
    INSERT INTO wflow.gestiones AS gestion (workflow_session, usuario_asesor, numero_conexion, pqr)
    VALUES (p_session, btrim(p_datos->>'usuario_asesor'), btrim(p_datos->>'numero_conexion'), btrim(p_datos->>'pqr'))
    ON CONFLICT (workflow_session) DO NOTHING;
    -- Recuperar la referencia permite confirmar también un reintento sin UPDATE.
    SELECT * INTO STRICT inicio FROM wflow.gestiones WHERE workflow_session = p_session;
    datos := jsonb_build_object('usuario_asesor', inicio.usuario_asesor,
        'numero_conexion', inicio.numero_conexion, 'pqr', inicio.pqr);
    INSERT INTO wflow.gestiones_log
      (workflow_session, codigo_flujo, nombre_flujo, codigo_etapa, nombre_etapa,
       numero_etapa, numero_intento, execution_id, workflow_version, estado_gestion,
       resultado, next_step, respuestas_json, contexto_json)
    VALUES (inicio.workflow_session, 'inicioGestion', 'Inicio de gestion', 'registroInicial',
       'Datos iniciales del asesor y la atencion', 0, 1, p_execution_id, p_version,
       'Completada', 'datos_iniciales_registrados', 'fin_flujo_0', datos, datos)
    ON CONFLICT (workflow_session, codigo_flujo, codigo_etapa, numero_intento)
    DO NOTHING;
    RETURN QUERY SELECT 1, inicio.workflow_session::text, inicio.usuario_asesor::text,
        inicio.numero_conexion::text, inicio.pqr::text;
END $$;
REVOKE ALL ON FUNCTION wflow.registrar_inicio_gestion(text, jsonb, text, text) FROM PUBLIC;

CREATE OR REPLACE VIEW wflow.vw_gestiones_trazabilidad AS SELECT * FROM wflow.gestiones_log;
CREATE OR REPLACE VIEW wflow.vw_gestiones_resumen AS
SELECT g.workflow_session, g.usuario_asesor, g.numero_conexion, g.pqr, g.created_at AS inicio_gestion,
    MAX(l.updated_at) AS ultima_actualizacion, COUNT(l.id) AS registros,
    COALESCE(jsonb_agg(jsonb_build_object('codigo_flujo', l.codigo_flujo,
        'codigo_etapa', l.codigo_etapa, 'numero_etapa', l.numero_etapa,
        'numero_intento', l.numero_intento, 'resultado', l.resultado,
        'estado_gestion', l.estado_gestion, 'next_step', l.next_step)
        ORDER BY l.numero_etapa, l.numero_intento) FILTER (WHERE l.id IS NOT NULL), '[]'::jsonb) AS etapas
FROM wflow.gestiones g LEFT JOIN wflow.gestiones_log l USING (workflow_session)
GROUP BY g.id;
CREATE OR REPLACE VIEW wflow.vw_nsf_trazabilidad AS
SELECT * FROM wflow.gestiones_log WHERE codigo_flujo = 'ningunServicioFunciona';
CREATE OR REPLACE VIEW wflow.vw_nsf_resumen AS
SELECT workflow_session, MAX(usuario_asesor) AS usuario_asesor,
    MAX(numero_conexion) AS numero_conexion, MAX(pqr) AS pqr,
    MIN(created_at) AS inicio_gestion, MAX(updated_at) AS ultima_actualizacion,
    MAX(numero_etapa) AS ultima_etapa_registrada,
    MAX(resultado) FILTER (WHERE numero_etapa = 1) AS resultado_etapa_1,
    MAX(resultado) FILTER (WHERE numero_etapa = 2) AS resultado_etapa_2,
    MAX(resultado) FILTER (WHERE numero_etapa = 3) AS resultado_etapa_3,
    COALESCE(MAX(estado_gestion) FILTER (WHERE numero_etapa = 3),
        MAX(estado_gestion) FILTER (WHERE numero_etapa = 2),
        MAX(estado_gestion) FILTER (WHERE numero_etapa = 1)) AS estado_actual,
    MAX(next_step) FILTER (WHERE numero_etapa = 1) AS siguiente_paso_etapa_1,
    MAX(next_step) FILTER (WHERE numero_etapa = 2) AS siguiente_paso_etapa_2,
    MAX(next_step) FILTER (WHERE numero_etapa = 3) AS siguiente_paso_etapa_3,
    MAX(respuestas_json->>'tipo_sim') FILTER (WHERE numero_etapa = 1) AS tipo_sim,
    MAX(respuestas_json->>'qr_escaneo_ok') FILTER (WHERE numero_etapa = 2) AS qr_escaneo_ok,
    MAX(respuestas_json->>'linea_portada') FILTER (WHERE numero_etapa = 2) AS linea_portada,
    MAX(respuestas_json->>'portacion_completada') FILTER (WHERE numero_etapa = 2) AS portacion_completada,
    MAX(respuestas_json->>'suma_ok') FILTER (WHERE numero_etapa = 2) AS suma_ok,
    MAX(respuestas_json->>'tipo_falla_equipo') FILTER (WHERE numero_etapa = 3) AS tipo_falla_equipo,
    MAX(respuestas_json::text) FILTER (WHERE numero_etapa = 1) AS respuestas_etapa_1_json,
    MAX(respuestas_json::text) FILTER (WHERE numero_etapa = 2) AS respuestas_etapa_2_json,
    MAX(respuestas_json::text) FILTER (WHERE numero_etapa = 3) AS respuestas_etapa_3_json
FROM wflow.gestiones_log WHERE codigo_flujo = 'ningunServicioFunciona'
GROUP BY workflow_session;
COMMIT;
